print("Hello Exceptions")

'''Exercise 161 - Exceptions
Fix the code below so that it doesn't generate a SyntaxError.
Hint! The result should be 20 200'''

x = [1, 2]
y = [10, 100]

for i in x:
    for j in y:
        if i % 2 == 0:
            print(i * j)

'''Exercise 162 - Exceptions
Fix the code below so that it doesn't generate a SyntaxError.

Hint! The result should be 20 200'''


print("-------------")
x = [1, 2]
y = [10, 100]

for i in x:
    for j in y:
        if i % 2 == 0:
            print(i * j)


'''Exercise 163 - Exceptions
Fix the code below so that it doesn't generate a NameError.

Hint! The result should be 20 200'''

print("-------------")
x = [1, 2]
y = [10, 100]

for i in x:
    for j in y:
        if i % 2 == 0:
            print(i * j)


'''Exercise 164 - Exceptions
Fix the code below so that it doesn't generate a TypeError.

Hint! The result should be 20 200'''

print("-------------")
x = [1, 2]
y = [10, 100]

for i in x:
    for j in y:
        if i % 2 == 0:
            print(i * j)

'''Exercise 165 - Exceptions
Fix the code below so that it doesn't generate an IndexError.

Hint! The result should be 200 200'''

print("-------------")
x = [1, 2]
y = [10, 100]

for i in x:
    for j in y:
        if i % 2 == 0:
            print(x[1] * y[1])

'''Exercise 166 - Exceptions
Add the necessary clause(s) to the code below so that in case the ZeroDivisionError exception is raised then the program prints out Zero! to the screen.

'''
print("-------------")

try:
    20 % 2 == 0
    print("zero")
except ZeroDivisionError:
    print("Error Error Error")
else:
    print("Zero")


'''Exercise 167 - Exceptions
Add the necessary clause(s) to the code below so that in case the code under try raises no exceptions then the program prints out the result of 
the math operation and the string Clean! to the screen.'''

print("-------------")

try:
    print(25 % 5 ** 5 + 5)
except:
    print("Bug!")
else:
    print("Clean!")

'''
Exercise 168 - Exceptions
Add the necessary clause(s) to the code below so that no matter if the code under try raises any exceptions or not, 
then the program prints out the string Result! to the screen.'''

print("-------------")

try:
    print(25 % 0 ** 5 + 5)
except:
    print("Bug!")
finally:
    print("Result")

'''Exercise 169 - Exceptions
Add the necessary clause(s) to the code below so that in case the code under try raises the ZeroDivisionError exception then the program prints
out the string Zero! to the screen; additionally, if the code under try raises the IndexError exception then the program prints out the string Index!
   to the screen.'''


print("-------------")

x = [1, 9, 17, 32]

try:
    print(x[3] % 3 ** 5 + x[4])
except ZeroDivisionError:
    print("Zero!")
except IndexError:
    print("Index")


'''Exercise 170 - Exceptions
Add the necessary clause(s) to the code below so that in case the code under try raises no exceptions then the program prints out the result of the math 
operation and the string Clean! to the screen. If the code under try raises the ZeroDivisionError exception then the program prints Zero! to the screen. 
Ultimately, regardless of the result generated by the code under try, the program should print out Finish! to the screen.'''


print("-------------")

try:
    print(25 % 5 ** 5 + 5)
except ZeroDivisionError:
    print("Zero")
else:
    print("Result")
finally:
    "Finish"